name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0, v2.1)
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: sudo apt-get install -y build-essential  # Install build tools

      - name: Build project
        run: ../configure && make  # Adjust this command if you're using a different build system

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}  # Use the tag that triggered the workflow
          files: ./build/blz-ad-${{ github.ref }}  # Adjust to your built executable path
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub

  # Optionally, add a job to run tests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test  # Adjust to your test command
